### ISSUE TITLE
After an upgrade 

### ISSUE THREAD

**Issue by basz** [shipshapecode/ember-shepherd#94]
After upgrading to ember 2.10.0 I'm getting an exception for shepherd. When I remove it from my app thing work again...

ideas?

```
shepherd.js:25 Uncaught TypeError: Cannot read property 'Utils' of undefined(…)
(anonymous function) @ shepherd.js:25
(anonymous function) @ shepherd.js:9
(anonymous function) @ shepherd.js:11

loader.js:219 Uncaught Error: Could not find module `ember-resolver` imported from `plhw-client/resolver`(…)
missingModule @ loader.js:219
findModule @ loader.js:230
Module.findDeps @ loader.js:170
findModule @ loader.js:233
Module.findDeps @ loader.js:170
findModule @ loader.js:233
requireModule @ loader.js:20
(anonymous function) @ app-boot.js:4

```

**Comment by rwwagner90** [comment]
@basz it works with older ember? Do you have ember-resolver installed?

**Comment by basz** [comment]
It did, yes.
But i confess I upgrade last week and then things still worked. I cleanup node_modules and bower and reinstalled everything which exposed this problem.

ember-resolver is installed yes and is not problematic when ember-shepard is removed from the project.

**Comment by rwwagner90** [comment]
@basz could you try something for me? Can you `ember install ember-tether` and then see if it works please?

**Comment by basz** [comment]
hmm. I had removed that too...

```
ember install ember-tether
ember serve
= fine
```
then 
```
ember install ember-shepherd
ember serve
= fine
```
installs
```
    "ember-tether": "0.3.1",
    "ember-shepherd": "2.4.1",
```

now no error. weird... no idea what went wrong here. thanks

**Comment by rwwagner90** [comment]
@basz can you uninstall `ember-tether` and see if the issue comes back? I suspect I may need to add installing `ember-tether` to the blueprints for this addon.

**Comment by rwwagner90** [comment]
@basz it seems `ember-tether` needed to be a peerDependency. I have released version 2.4.2 of ember-shepherd with that change. You should be able to remove ember-tether and ember-shepherd, and reinstall, and it will pull in both. Thanks for bringing this to my attention!

**Comment by basz** [comment]
i see what you mean, but this did not fix it. I still need to manually do `ember install ember-tether`

**Comment by rwwagner90** [comment]
@basz are you sure? Delete `ember-tether` and `ember-shepherd` from package.json, then run:

`rm -rf node_modules`
`npm cache clean`
`ember install ember-shepherd`

Let me know if that works please!

**Comment by rwwagner90** [comment]
@basz it seems that no combination of deps, peerDeps, etc fix the issue, so I added a blueprint to add `ember-tether` when you `ember install ember-shepherd`. Can you please remove them and give it a shot?

**Comment by basz** [comment]
```
rm -rf node_modules
npm cache clean
nom install
ember install ember-shepherd
Installed packages for tooling via npm.
installing ember-shepherd
  install addon ember-tether
Installed packages for tooling via npm.
Installed addon package.
Installed addon package.
```
```
ember serve >> party!
```

resolved, thanks
